name: Generate tokens on commit

on:
  push:
    paths:	
      - '**/**.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Node Dependencies
        run: npm install
      - name: Build Style Dictionary
        run: npm run build
      - name: Commit Generated Platform Deliverables
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update design tokens
