name: Generate tokens on commit

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install node dependencies
        run: yarn
      - name: Delete old tokens
        run: yarn clean
      - name: Build tokens
        run: yarn build
      - name: Commit generated output deliverables
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update design tokens
