name: Generate tokens on commit

on:
  push:
    paths:
      - '**/**.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install node dependencies
        run: npm install
      - name: Delete old tokens
        run: npm run clean
      - name: Build tokens
        run: npm run build
      - name: Commit generated output deliverables
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update design tokens
